name: Build JPG Converter EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow pyinstaller

    - name: Build EXE
      run: |
        pyinstaller --noconsole --onefile jpg_converter_gui_progress.py

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v3
      with:
        name: jpg-converter-exe
        path: dist/jpg_converter_gui_progress.exe
